<?xml version="1.0" encoding="utf-8"?><Database Name="DAWEBTHOITRANG" Class="doanwebthoitrangDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-S1N3U42\SQLEXPRESS;Initial Catalog=DAWEBTHOITRANG;Integrated Security=True" SettingsObjectName="ThoiTrangAPI.Properties.Settings" SettingsPropertyName="DAWEBTHOITRANGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSP" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiamGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaLoai" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="Anh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AnhCT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>