//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWebNam3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietHDs = new HashSet<ChiTietHD>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public string MoTa { get; set; }
        public string MaNCC { get; set; }
        public string MaLoai { get; set; }
        public string Anh { get; set; }
        public string AnhCT { get; set; }
        public string Size { get; set; }
    
        public virtual ICollection<ChiTietHD> ChiTietHDs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
